"""Shared layout measurements for the desktop control-panel UI."""

PAGE_GUTTER = 32
PAGE_TOP = 16
PAGE_BOTTOM = 24
SECTION_GAP = 16
CARD_GAP = 16
CARD_PADDING = 16
CONTROL_HEIGHT = 38
PRIMARY_CONTROL_HEIGHT = 54
BOARD_CONTROL_HEIGHT = 54
ROW_HEIGHT = 48
RADIUS = 6
SIDEBAR_WIDTH = 250
NAV_ROW_HEIGHT = 44
